vhdl-sources += jtag_spi.vhd
constraint-sources += ../$(target_part)/pinout.ucf
deps += nsl_hwdep.clock
deps += nsl_hwdep.reset
deps += nsl_spi.transactor
deps += nsl_bnoc.framed
deps += nsl_jtag.fifo_transport
