vhdl-sources += jtag_swapped.vhd
deps += nsl_indication.activity
constraint-sources += ../../pinout/ftdi_jtag.ucf
constraint-sources += ../../pinout/io0_dbg.ucf
constraint-sources += ../../pinout/user.ucf
constraint-sources += ../../pinout/clk.ucf
