vhdl-sources += func.pkg.vhd
vhdl-sources += jtag_spi.vhd
deps += nsl_hwdep.clock
deps += nsl_hwdep.reset
deps += nsl_spi.transactor
deps += nsl_bnoc.framed
deps += nsl_jtag.fifo_transport
deps += nsl_indication.activity
